Woven-dojo/dojo-frontend-app-learner-portal

src/components/course/data/hooks.jsx
src/components/course/data/service.js
src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx
src/components/dashboard/main-content/course-enrollments/CourseEnrollmentsContextProvider.jsx
src/components/dashboard/main-content/course-enrollments/data/hooks.js
src/components/dashboard/main-content/course-enrollments/data/service.js
src/components/enterprise-banner/EnterpriseBanner.jsx
src/components/enterprise-user-subsidy/UserSubsidy.jsx
src/components/enterprise-user-subsidy/data/hooks.js
src/components/enterprise-user-subsidy/data/service.js
src/components/program/data/service.js
src/components/search/Search.jsx
src/components/search/SearchCourseCard.jsx
src/components/search/SearchProgramCard.jsx

https://woven-dojo.atlassian.net/browse/DAD-314

[DAD-314] Modified learner portal to use our own catalog

---

src/components/dashboard/Dashboard.jsx
src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx
src/components/layout/MainContent.jsx

https://woven-dojo.atlassian.net/browse/DAD-317

[DAD-317] Remove Courses section and 'Need Help' side panel

---

src/components/search/Search.jsx

https://woven-dojo.atlassian.net/browse/DAD-317

[DAD-317] Fix markup for program list

---

.gitignore
package-lock.json
package.json
src/components/course/data/service.js

- Fix brand library not being pulled

[NO-STORY] Fix brand library

---

.gitignore
package-lock.json
package.json
src/components/course/data/service.js

Reverts reustleco/dojo-frontend-app-learner-portal#7

Revert "[NO-STORY] Fix brand library"

---

package-lock.json
package.json
src/components/enterprise-user-subsidy/data/service.js
src/components/search/Search.jsx
src/components/search/SearchCourseCard.jsx
src/components/search/styles/_SearchContentCard.scss
src/components/search/tests/SearchCourseCard.test.jsx

https://woven-dojo.atlassian.net/browse/DP-225

[DP-225] Implemented catalog POC UI

---

src/__snapshots__/smoke.test.jsx.snap
src/components/app/App.jsx
src/components/app/AuthenticatedPage.jsx
src/components/app/LoginRedirect.jsx
src/components/app/__snapshots__/AuthenticatedPage.test.jsx.snap
src/components/dashboard/main-content/DashboardMainContent.jsx
src/components/enterprise-page/EnterprisePage.jsx
src/components/search/CatalogNoResults.jsx
src/components/search/Search.jsx
src/components/site-header/SiteHeader.jsx

https://woven-dojo.atlassian.net/browse/DP-225

[DP-225] QA fixes

---

src/components/app/App.jsx
src/components/app/AuthenticatedPage.jsx
src/components/app/__snapshots__/AuthenticatedPage.test.jsx.snap
src/components/dashboard/main-content/DashboardMainContent.jsx
src/components/enterprise-redirects/EnterprisePageRedirect.jsx
src/components/enterprise-redirects/tests/EnterprisePageRedirect.test.jsx
src/components/site-header/AvatarDropdown.jsx
src/components/site-header/SiteHeader.jsx
src/components/site-header/tests/SiteHeader.test.jsx

https://woven-dojo.atlassian.net/browse/DP-272

[DP-272] Changed routing

---

src/components/site-header/SiteHeader.jsx

Fixing enteprise logo link to redirect to the right place.

[DP-272] Fixing logo link

---

src/components/dashboard/Dashboard.jsx
src/components/dashboard/styles/_Dashboard.scss
src/components/dashboard/tests/Dashboard.test.jsx
src/components/enterprise-user-subsidy/UserSubsidy.jsx
src/components/enterprise-user-subsidy/data/hooks.js
src/components/enterprise-user-subsidy/data/service.js

https://woven-dojo.atlassian.net/browse/DP-307
- add logic for fetching learning path data
- show learning path data on the dashboard
- show catalog data on the dashboard
- fix small differences from the latest design

[DP-307] Connect learning path and catalog API

---

jest.config.js
package-lock.json
package.json
src/components/dashboard/Dashboard.jsx
src/components/dashboard/tests/Dashboard.test.jsx

https://woven-dojo.atlassian.net/browse/DP-306
- Use CourseCard component instead of the `SearchCourseCard`.
- Fix the Jest config for it to load components from dojo-frontend-common

[DP-306] Use CourseCard component on the dashboard

---

.github/pull_request_template.md

- Add more detailed template from JIRA.

[NO-STORY] Update the PR template

---

package-lock.json
package.json
src/components/course/tests/__snapshots__/Course.test.jsx.snap
src/components/dashboard/Dashboard.jsx
src/components/dashboard/sidebar/SidebarCard.jsx
src/components/dashboard/styles/_Dashboard.scss
src/components/dashboard/styles/_Pagination.scss
src/components/pathway/SearchPathwayCard.jsx
src/components/search/SearchCourseCard.jsx
src/components/search/SearchProgramCard.jsx
src/components/skills-quiz/CardLoadingSkeleton.jsx
src/components/skills-quiz/CourseCard.jsx
src/components/skills-quiz/JobCardComponent.jsx
src/components/skills-quiz/SearchProgramCard.jsx
src/components/skills-quiz/SelectJobCard.jsx
src/index.scss

https://woven-dojo.atlassian.net/browse/DP-305
- Update the `@edx/paragon` to a newer version.
- Add client side pagination at the bottom of the catalog.
- Wrap catalog items in the `TransitionReplace` component to avoid quick flickering when re-rendering.
- Used update Card from paragon in a few components so we pass tests for them. 
- https://paragon-openedx.netlify.app/changelog#breaking-changes-1

[DP-305] Add pagination for the catalog

---

src/components/dashboard/Dashboard.jsx

https://woven-dojo.atlassian.net/browse/DP-293
-

[DP-293] Fix title of the learning path header

---

src/components/app/App.jsx
src/components/app/AuthenticatedPage.jsx
src/components/site-header/SiteHeader.jsx

https://woven-dojo.atlassian.net/browse/DCS-90 
- Remove navigation links from the header.
- Remove the enterprise banner from the dashboard.

[DCS-90] Remove search routes

---

src/components/dashboard/Dashboard.jsx

| Desktop | Mobile |
|---|---|
|![image](https://user-images.githubusercontent.com/90377295/188701623-e34bc4d6-b623-4a53-9dd5-ee905993ebd0.png)|![image](https://user-images.githubusercontent.com/90377295/188701672-9fb1d3a8-30ef-4681-b457-009b231bfdd8.png)|
This PR adds the "Survey" link to users that have it set in their profile.

[DCS-114] Add kickoff survey link

---

.npmrc
src/utils/common.js

https://woven-dojo.atlassian.net/browse/DCS-115
- if there is no primary language, default value is '-'
- 'en' displayed ENG
- 'jp' displayed 日本
- 'ja' displayed 日本

[DP-115] Show proper language names, not code

---

src/components/enterprise-user-subsidy/data/constants.js
src/components/enterprise-user-subsidy/data/hooks.js

https://woven-dojo.atlassian.net/browse/DCS-120
The previous logic used hardcoded IDs for the filtering, but depending on the order we added them to the DB it would be differnt per env etc. To fix that we asked BE team to expose the internal ID on the API and we're filtering using those.

DCS-120 Adjust filtering logic to new backend response, remove delivery method

---

src/components/dashboard/Dashboard.jsx
src/components/dashboard/styles/_DashboardDrawer.scss
src/components/enterprise-user-subsidy/UserSubsidy.jsx
src/components/enterprise-user-subsidy/data/hooks.js
src/components/enterprise-user-subsidy/data/service.js

https://woven-dojo.atlassian.net/browse/DCS-117
| EDX Course | Request access | Access request success | Access already requested |
|---|---|---|---|
|![image](https://user-images.githubusercontent.com/90377295/188993540-339e2f42-eb64-4267-967c-902b7c391e3b.png)|![image](https://user-images.githubusercontent.com/90377295/188993837-87583c3d-14a1-4cc3-ac27-a54f62bcd6b7.png)|![image](https://user-images.githubusercontent.com/90377295/188993766-2ecb9416-86a3-4064-9fcd-1dce7b67e63e.png)|![image](https://user-images.githubusercontent.com/90377295/188993801-ea6ccd46-7339-4b60-a0fe-5ca0a625cea3.png)|
Discussed on Slack with Eric that we can use Toast instead of Modal

DCS-117 Handle course request lifecycle button

---

src/components/dashboard/Dashboard.jsx

https://woven-dojo.atlassian.net/browse/DCS-117
None
Make sure to use the edx_course_id to handle self-hosted courses.

DCS-117 Use course_id for the button logic

---

src/utils/common.js
src/utils/common.test.js

https://woven-dojo.atlassian.net/browse/DCS-115
None
Support nullish values in the helper

DCS-115 Support nullish languages

---

src/components/dashboard/Dashboard.jsx
src/components/dashboard/styles/_Dashboard.scss
src/components/dashboard/styles/_Pagination.scss
src/components/filter/styles/_Filter.scss

https://woven-dojo.atlassian.net/browse/DCS-145
https://woven-dojo.atlassian.net/browse/DCS-146
https://woven-dojo.atlassian.net/browse/DCS-147
None
This PR addresses various small UI defects identified during early QA

[DCS-145] [DCS-146] [DCS-147] Fix chip height and margins/paddings 

---

src/components/dashboard/Dashboard.jsx
src/components/dashboard/DashboardPanel.jsx

NO JIRA
| #course-catalog | #learning-path |
|---|---|
|![image](https://user-images.githubusercontent.com/90377295/189293172-61cf7e6c-5a7a-4a0c-a69d-f54750a937e4.png)|![image](https://user-images.githubusercontent.com/90377295/189293217-62f6d248-acef-4107-bb57-0852a56e8313.png)|
Adding anchors so we can use them in emails and other communication

NO-JIRA: Add anchors to panels

---

src/components/dashboard/Dashboard.jsx

https://woven-dojo.atlassian.net/browse/DCS-145
Re-adding the margin (it got lost because we changed the way cards are spaced)

DCS-145 Add marigin on top of pagination

---

src/components/dashboard/Dashboard.jsx
src/components/dashboard/styles/_Dashboard.scss

https://woven-dojo.atlassian.net/browse/DCS-144
Side by side figma and website:
Make sure the design aligns with figma.

DCS-144 Fix header spacing

---

src/components/dashboard/Dashboard.jsx
src/components/dashboard/data/constants.js

https://woven-dojo.atlassian.net/browse/DCS-125
This PR is about keeping the focus on course card correctly

[DCS-125] Course application button text

---

src/components/error-page/ErrorPage.jsx
src/components/error-page/__snapshots__/ErrorPage.test.jsx.snap
src/components/layout/Layout.jsx
src/components/layout/styles/Layout.scss
src/components/layout/tests/__snapshots__/Layout.test.jsx.snap

https://woven-dojo.atlassian.net/browse/DCS-149
The current footer has hardcoded link to opendx website and also loads the image from their CDN.

DCS-149 Replace the footer with Dojo one

---

package-lock.json
package.json
src/components/Toasts/Toasts.jsx
src/components/Toasts/ToastsProvider.jsx
src/components/Toasts/hooks.js
src/components/Toasts/index.js
src/components/Toasts/utils.js
src/components/app/App.jsx
src/components/dashboard/Dashboard.jsx

https://woven-dojo.atlassian.net/browse/DCS-150
- add stacking of the toasts, use the actual ToastProvider implemented (and not used) in openedX
- update the message to remove email

DCS-150 Stack toasts, update message

---

src/components/site-header/SiteHeader.jsx
src/components/site-header/tests/SiteHeader.test.jsx

https://woven-dojo.atlassian.net/browse/DCS-152
N/A
Remove the link element

DCS-152 Remove link on the enterprise logo

---

package-lock.json
package.json

https://woven-dojo.atlassian.net/browse/DCS-151
Update the frontend-common in order to support formated course description content.

DCS-151 Bump version of frontend-common

---

package-lock.json
package.json
src/components/dashboard/Dashboard.jsx
src/components/dashboard/tests/Dashboard.test.jsx

https://woven-dojo.atlassian.net/browse/DCS-154
https://woven-dojo.atlassian.net/browse/DCS-155
This PR is about displaying mark '-' for Course Card and Details, when value doesn't exist

[DCS-154] [DCS-155] fixed default values

---

src/components/dashboard/styles/_Dashboard.scss

https://woven-dojo.atlassian.net/browse/DCS-156
This PR is about incising routing of the corners for dashboard panel from 4px to 8px

[DCS-156] Increase rounding of the corners

---

src/utils/common.js

NO-JIRA
N/A
Fixing a typo in the 'Japanese' label

Correct spelling for 'Japanese'

---

package-lock.json
package.json
src/components/dashboard/Dashboard.jsx
src/components/dashboard/DashboardPage.jsx
src/components/dashboard/DashboardPanel.jsx
src/components/dashboard/data/steps.jsx
src/components/dashboard/styles/_Dashboard.scss
src/components/dashboard/styles/_DashboardPage.scss
src/components/dashboard/utils/common.js
src/index.scss

https://woven-dojo.atlassian.net/browse/DCS-166
This PR is about adding a “spotlight” tutorial

[DCS-166] Spotlight tutorial

---

package-lock.json
package.json

n/a
- update `dojo-frontend-common` to fix install issue

chore: update dojo-frontend-common

---

package-lock.json
package.json
src/components/app/App.jsx
src/components/dashboard/Dashboard.jsx
src/components/enterprise-user-subsidy/UserSubsidy.jsx
src/components/enterprise-user-subsidy/data/constants.js
src/components/enterprise-user-subsidy/data/hooks.js
src/components/enterprise-user-subsidy/data/service.js
src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx
src/components/filter/Filter.jsx

https://woven-dojo.atlassian.net/browse/DCS-197
This PR relates to the addition of an additional control function for filters

[DSC-197] Consume the Feature Flag config on BE and control filter behaviour

---

package-lock.json
package.json
src/components/error-page/ErrorPage.jsx
src/components/error-page/__snapshots__/ErrorPage.test.jsx.snap
src/components/layout/Layout.jsx
src/components/layout/styles/Layout.scss
src/components/layout/tests/__snapshots__/Layout.test.jsx.snap

https://woven-dojo.atlassian.net/browse/DCS-80
This PR is about removing removing unnecessary classes and wrapping container for header

[DSC-80] Include Dojo branding in edx packages currently in use

---

package-lock.json
package.json
src/components/enterprise-user-subsidy/UserSubsidy.jsx
src/components/enterprise-user-subsidy/data/constants.js
src/components/enterprise-user-subsidy/data/hooks.js
src/components/filter/Filter.jsx

https://woven-dojo.atlassian.net/browse/DCS-231
This PR is about adding search capabilities to Filters

[DSC-231] Search capabilities

---

src/components/dashboard/Dashboard.jsx
src/components/dashboard/DashboardPage.jsx
src/components/dashboard/styles/_DashboardPage.scss

https://woven-dojo.atlassian.net/browse/DCS-243
This PR fix tutorial behaviour when resizing the screen 
* [x Have you included the task ID in the PR title? (Format: `[ABC-###] - PR title`)

[DSC-243] Wrong tutorial behaviour

---

package-lock.json
package.json
src/components/dashboard/Dashboard.jsx
src/components/dashboard/data/constants.js
src/components/enterprise-user-subsidy/UserSubsidy.jsx
src/components/enterprise-user-subsidy/data/constants.js
src/components/enterprise-user-subsidy/data/hooks.js

https://woven-dojo.atlassian.net/browse/DCS-232
This PR is about adding sorting capabilities

[DSC-232] Sorting capabilities

---

src/components/dashboard/Dashboard.jsx
src/components/enterprise-user-subsidy/UserSubsidy.jsx
src/components/enterprise-user-subsidy/data/constants.js
src/components/enterprise-user-subsidy/data/hooks.js
src/components/filter/Filter.jsx
src/components/utils/constants.js
src/components/utils/hooks.js

https://woven-dojo.atlassian.net/browse/DCS-235
This PR considerd storing the input values (search, sort, filter, paginate) as part of the URL so that the pages can be bookmarked or shared with peers.

[DSC-235] Search parameter persistence
